/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://gkh3p3lplfgchowrrnaaju2cje.appsync-api.eu-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "null",
    "aws_content_delivery_bucket": "awsmobileappsynceven-20201109193714-hostingbucket-awsappsync",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://awsmobileappsynceven-20201109193714-hostingbucket-awsappsync.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
